<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-22T21:11:23 CDT" name="Default suite" finished-at="2025-06-22T21:11:23 CDT" duration-ms="21">
    <groups>
    </groups>
    <test started-at="2025-06-22T21:11:23 CDT" name="Default test" finished-at="2025-06-22T21:11:23 CDT" duration-ms="21">
      <class name="testng.TestNGDemo3">
        <test-method signature="test4()[pri:-2, instance:testng.TestNGDemo3@478190fc]" started-at="2025-06-22T21:11:23 CDT" name="test4" finished-at="2025-06-22T21:11:23 CDT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method signature="newtest1()[pri:-1, instance:testng.TestNGDemo3@478190fc]" started-at="2025-06-22T21:11:23 CDT" name="newtest1" finished-at="2025-06-22T21:11:23 CDT" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Message Verification failed:  expected [Obhi] but found [obhi]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Message Verification failed:  expected [Obhi] but found [obhi]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testng.TestNGDemo3.newtest1(TestNGDemo3.java:12)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newtest1 -->
        <test-method signature="newtest2()[pri:0, instance:testng.TestNGDemo3@478190fc]" started-at="2025-06-22T21:11:23 CDT" name="newtest2" finished-at="2025-06-22T21:11:23 CDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newtest2 -->
        <test-method signature="newtest3()[pri:0, instance:testng.TestNGDemo3@478190fc]" started-at="2025-06-22T21:11:23 CDT" name="newtest3" finished-at="2025-06-22T21:11:23 CDT" depends-on-methods="testng.TestNGDemo3.newtest1" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testng.TestNGDemo3.newtest3() on instance testng.TestNGDemo3@478190fc depends on not successfully finished methods 
[testng.TestNGDemo3.newtest1() on instance testng.TestNGDemo3@478190fc]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testng.TestNGDemo3.newtest3() on instance testng.TestNGDemo3@478190fc depends on not successfully finished methods 
[testng.TestNGDemo3.newtest1() on instance testng.TestNGDemo3@478190fc]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newtest3 -->
        <test-method signature="test5()[pri:1, instance:testng.TestNGDemo3@478190fc]" started-at="2025-06-22T21:11:23 CDT" name="test5" finished-at="2025-06-22T21:11:23 CDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
      </class> <!-- testng.TestNGDemo3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
